Atualizando SQL para adicionar descrição do evento
wellintonpiassa/UNI pull request #7
Opened 2022-04-05 17:13 UTC by danilokassuya

# Breve descrição da feature implementada
Adicionado nas tabela evento do backend os campos para url da imagem do banner do evento e descrição do evento
# Procedimentos necessários para testar a feature

# Verificações
- [x] Revisor adicionado ao pull request.
- [x] Atividade movida para categoria "Em andamento" no Trello.
- [x] Alteração testada locamente.

2022-04-07 11:26 UTC, andrefcordeiro reviewed
Aprovado.

2022-04-09 14:24 UTC, VitorgsRuffo approved these changes
Tudo ok.

2022-04-09 14:26 UTC, VitorgsRuffo requested changes
Trocar branch de main para dev.

2022-04-09 14:27 UTC, merged

2022-04-09 14:43 UTC, VitorgsRuffo reviewed
ok